### PR TITLE
Add support for watch options and windows recursive watch

### PR DESCRIPTION
**Pull request by garyjN7**
#101 These changes allow atom's tree-view package to recursively watch files and directories under a root folder on windows.

### CODE REVIEW

**Comment by alexandernst** [comment]
Any news on this?

**Comment by vweevers** [comment]
@maxbrunsfeld Is there anything the community can do to help speed up (review of) this PR? This is a long-standing, painful issue for Windows users.

**Comment by iolsen** [comment]
@smashwilson would this co-exist with the changes you're working on? If so, would you be willing to review?

**Comment by iolsen** [comment]
Hey @garyjN7 thanks for the contribution! We're quite far along in the project to improve and unify Atom's file watching functionality and API: https://github.com/atom/watcher

Recursive watching on Windows is part of that. Rather that working to land this then undoing it when that lands, I'm going to just close this and ask you to be patient for atom/watcher to land. 😄

**Pull request closed without merging**
