### PR TITLE
Switch travis.yml to use nodejs

### PR DESCRIPTION
**Pull request by 50Wliu**
Just investigating if pathwatcher actually builds on Node 4.
Refs atom/text-buffer#99.

### CODE REVIEW

**Comment by 50Wliu** [comment]
@zcbenz can you look at the [npm install](https://travis-ci.org/atom/node-pathwatcher/jobs/80639995#L103) errors by any chance?  Thanks.

**Comment by zcbenz** [comment]
I think it is a bug of clang, we can use g++ >= 4.8 in CI to work around it.

**Comment by 50Wliu** [comment]
@zcbenz Unless I'm doing something wrong, g++-4.8 doesn't exist on Travis.

**Comment by zcbenz** [comment]
It needs to be installed from PPA, an example can be found at:
https://github.com/atom/node-oniguruma/blob/master/.travis.yml

And we also need to use GCC 4.8 for modules that depend on this module.

**Comment by 50Wliu** [comment]
Ok, the build's passing again, so that's :green_heart:.  Now the only thing left I think is that make keeps failing on the first pass with:
```
make: Entering directory `/home/travis/build/atom/node-pathwatcher/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
In file included from ../src/main.cc:1:0:
../../nan/nan.h:138:53: fatal error: nan_callbacks.h: No such file or directory
 #include "nan_callbacks.h"  // NOLINT(build/include)
```
but then succeeds on the second try.

**Comment by zcbenz** [comment]
Looks good to me, thanks!

**Comment by 50Wliu** [comment]
@zcbenz thanks so much for the help!
Though do you think the error above needs addressing or that it's fine?

**Comment by zcbenz** [comment]
I think it is fine to ignore that for now, if it still happens in future we can report it to NAN's repo.

**Pull request merged**
