### PR TITLE
Introduce File::existsSync() and deprecate File::exists().

### PR DESCRIPTION
**Pull request by bolinfest**

### CODE REVIEW

**Comment by bolinfest** [comment]
Once this is in:

* Bump `pathwatcher` to `3.3.0` in its own `package.json` and publish to npm.
* Bump `pathwatcher` to `3.3.0` in `text-buffer`.
* Replace `@file.exists()` with `@file.existsSync()` in https://github.com/atom/text-buffer/blob/master/src/text-buffer.coffee.
* Bump `text-buffer` to `4.1.5`.
* Bump `pathwatcher` to `3.3.0` and `text-buffer` to `4.1.5` in Atom.
* Replace `directory.getFile('HEAD').exists()` with `directory.getFile('HEAD').existsSync()` in `git-repository-provider.coffee`.

Profit.

**Comment by bolinfest** [comment]
Should I also update the comment for `exists()` about its deprecation so it appears in the HTML docs?

**Comment by bolinfest** [comment]
I guess the final step is to send out pull requests to the handful of Atom packages who are using `exists()` to get them to switch to `existsSync()` once the new version of Atom with `existsSync()` is published.

**Comment by kevinsawicki** [comment]
3.3 published with this in it, thanks!

**Pull request merged**
