### PR TITLE
Add encoding auto-detection logic

### LINKED ISSUE #51: Uncaught Error: "toString()" failed
_From @davibicudo on July 31, 2017 11:51_

[Enter steps to reproduce:]

1. Open a large file
2. Try to change encoding to AutoDetect option
Perhaps it has something to do with issue #7210 ?

**Atom**: 1.19.0-beta5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: "toString()" failed

```
At buffer.js:503

Error: "toString()" failed
    at Buffer.toString (buffer.js:503:11)
    at Object.jschardet.detect (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/jschardet/src/init.js:72:29)
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/encoding-selector/lib/encoding-list-view.js:143:53
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
```

### Commands

```
     -1:40.3.0 core:paste (input.input-text.native-key-bindings)
 13x -0:51.1.0 core:backspace (input.hidden-input)
     -0:38.9.0 grammar-selector:show (atom-text-editor.editor)
     -0:33 editor:consolidate-selections (input.hidden-input)
     -0:33 core:cancel (input.hidden-input)
     -0:30.4.0 encoding-selector:show (atom-text-editor.editor)
     -0:28.5.0 editor:consolidate-selections (input.hidden-input)
     -0:28.5.0 core:cancel (input.hidden-input)
  3x -0:27.7.0 encoding-selector:show (atom-text-editor.editor)
```

### Non-Core Packages

```
autocomplete-solidity 0.3.3 
etheratom 3.1.0 
linter-solidity 0.5.0 
```

_Copied from original issue: atom/atom#15134_

### PR DESCRIPTION
**Pull request by winstliu**
This is a possible fourth part to the move-encoding-detection-into-core saga.  If merged, it will allow https://github.com/atom/text-buffer/pull/220 to use these methods instead of having to require jschardet and iconv-lite by itself.

~~One thing that I'm not happy about is the use of `readFileSync`.  Making the whole chain use callbacks feels ugly to me and is also inconsistent with `setEncoding` and `getEncoding`, though it's definitely a possibility.~~

Fixes atom/encoding-selector#51

### CODE REVIEW

**Comment by 50Wliu** [comment]
Update: `readFileSync` is not going to be an acceptable solution, especially because this is done on file load.

**Comment by 50Wliu** [comment]
Caveats:
* The current test file for cp1255 is actually cp1252 (according to @Ben3eeE).
* Atom's `text-editor.js` is incorrectly detected as cp1252 instead of utf8.
* Since this is asynchronous now, I'm not sure what will happen if you manage to edit the file before the encoding is changed.

**Comment by nathansobo** [comment]
It's late on a Friday and I'm in a hurry, so please forgive me if any of this feedback is missing out on important details.

My concern with the approach in this group of PRs is that we do a lot of redundant I/O in the event that we're detecting a non-default encoding. We first do I/O in superstring to load the buffer before detecting the encoding, then we do I/O *again* to feed bytes to the jschardet, then we update the encoding triggering another reload.

It seems like we want to detect the encoding *before* loading the buffer at all. It seems like there are two options of varying difficulty to implement:

The first is to keep detection in JS and do a limited amount of I/O in `TextBuffer.load` in order to feed some bytes to `jschardet`. I would want a guarantee that we would stop if we didn't detect the encoding after some number of chunks so as not to read the entire file. Note that there are two code paths in `TextBuffer.load`, one taking a path and one taking a file.

The other approach is more optimal but harder to implement: Do the encoding detection in superstring in the [`load_file`](https://github.com/atom/superstring/blob/15d4e8cc9e40b80f1a4e9bc240d5c4c931baca13/src/bindings/text-buffer-wrapper.cc#L585) method. This method already does I/O and performs an encoding conversion. Perhaps it could be modified to optionally first *detect* the encoding based on the first batch of read bytes. This would avoid the redundant I/O but raise the difficulty and risk.

@maxbrunsfeld Do you have thoughts on this? How bad would it be to do enough I/O in the JS side of buffer loading to detect the encoding?

**Comment by maxbrunsfeld** [comment]
I'm not sure how long encoding detection takes, and how much data needs to be loaded. If we want it to happen on a background thread as part of superstring's file loading, we could definitely it in C++. The [uchardet](https://cgit.freedesktop.org/uchardet/uchardet) C++ library seems to be used by a lot of things.

**Comment by nathansobo** [comment]
@50Wliu want to try your hand at some C++?

**Comment by 50Wliu** [comment]
We'll see 😬 
I'll probably need a lot of hand-holding though.  Will be my first time writing anything C/C++.

**Comment by 50Wliu** [comment]
Ok, I took a look at uchardet.  This is my first time trying to understand C++ code so my analysis could be way off.

It looks like their model is "give us as many bytes as you have, and call `uchardet_get_charset(ud)` once you're finished".  The uchardet header doesn't expose confidence information so we can't opportunistically short-circuit if the confidence level is high enough, and on the flip side uchardet could also give us a charset that it's only 20% confident about and we wouldn't know any better.

So "detect[ing] the encoding based on the first batch of read bytes" may be unreliable using uchardet.  It would also misreport the encoding if the special characters are only later on in the file.

Thoughts?

**Comment by nathansobo** [comment]
@50Wliu In an auto-detection scenario, it might be okay to buffer up all the bytes (or up to some reasonable maximum) without transcoding them in order to hand them to to uchardet first. This would still be better than performing the actual I/O twice.

**Comment by calebmeyer** [comment]
Not sure if this helps, but it looks like this is what VS Code is doing for detection: https://github.com/Microsoft/vscode/pull/21416/files

They're also using the JSCharDet library

**Comment by 50Wliu** [comment]
https://github.com/atom/atom/pull/13943#issuecomment-930622479

**Pull request closed without merging**
