### PR TITLE
Use native promises instead of Q library

### PR DESCRIPTION
**Pull request by nathansobo**
Now that native promises work in Electron, there's no reason to continue using the Q library. Its API is nonstandard and it seems to swallow errors in unpredictable ways.

Since the API of Q's promises differs slightly from native promises, this requires a major version increment.

/cc @kevinsawicki since you've done a lot with pathwatcher.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
I think the ci build may need to be upgraded to node 0.12 for this.

**Comment by leipert** [comment]
What about the usage in atom packages? apm uses still node 0.10

pathwatcher is used in [markdown-preview](https://github.com/atom/markdown-preview) for example.

/cc @kevinsawicki as you seem to contribute to markdown-preview

**Comment by nathansobo** [comment]
> What about the usage in atom packages?

Definitely won't upgrade any Atom packages without running specs and fixing any breaking API calls.

**Comment by leipert** [comment]
Thank you for the info.

**Pull request merged**
